openapi: 3.0.0
info:
  title: User Registration API
  description: API documentation for the User Registration system
  version: 1.0.0

servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
              required:
                - email
                - username
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: User already exists
        '500':
          description: Internal server error

  /api/auth/verify:
    post:
      summary: Verify a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                otp:
                  type: string
              required:
                - email
                - otp
      responses:
        '200':
          description: User verified successfully
        '400':
          description: Invalid email or OTP
        '500':
          description: Internal server error

  /api/auth/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful, returns JWT token
        '400':
          description: Invalid email or password
        '500':
          description: Internal server error

  /api/user/add-info:
    post:
      summary: Add extra information to user profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                age:
                  type: number
                work:
                  type: string
                dob:
                  type: string
                  format: date
                description:
                  type: string
      responses:
        '200':
          description: User information updated successfully
        '404':
          description: User not found
        '500':
          description: Internal server error

  /api/user/info:
    get:
      summary: Get user information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Returns user information
        '404':
          description: User not found
        '500':
          description: Internal server error

  /api/user/update-info:
    patch:
      summary: Update user information
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                location:
                  type: string
                age:
                  type: number
                work:
                  type: string
                dob:
                  type: string
                  format: date
                description:
                  type: string
      responses:
        '200':
          description: User information updated successfully
        '400':
          description: Invalid updates
        '404':
          description: User not found
        '500':
          description: Internal server error

  /api/admin/register:
    post:
      summary: Register a new admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
              required:
                - email
                - username
                - password
      responses:
        '201':
          description: Admin registered successfully
        '400':
          description: Admin already exists
        '500':
          description: Internal server error

  /api/admin/login:
    post:
      summary: Login an admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful, returns JWT token
        '400':
          description: Invalid email or password
        '500':
          description: Internal server error

  /api/admin/users:
    get:
      summary: Get all users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Returns list of usernames
        '500':
          description: Internal server error

  /api/admin/users/{username}:
    get:
      summary: Get user details
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: Username of the user to get details
      responses:
        '200':
          description: Returns user details
        '404':
          description: User not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a user
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: Username of the user to delete
      responses:
        '200':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Internal server error
